# Numpy
### Es el paquete fundamental para computo científico en python, se pueden realizar calculos estadísticos 

In [2]:
#importamos la libreria
import numpy as np

#Creamos una lista con números primos
numPrimos=[2,3,5,7,11,13,17,19,23,29]
numPrimos

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29]

In [3]:
#creamos un array con los numeros primos de nuestra lista
arraynprimos=np.array(numPrimos)
arraynprimos

array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29])

In [4]:
#podemos crear tambien un array llenandolo unicamente con valores 0
arrZero=np.zeros(10)
arrZero

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
#al igual que el ejemplo anterior podemos rellenar el array con numeros estableciendo un rango
arrNum=np.arange(11)
arrNum

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
#para realizar el ejercicio con numeros pares se usa arrange, donde definimos el numero inicial, el final y el paso
arrPar=np.arange(0, 21, 2)
arrPar

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [11]:
#para trabajar la informacion con filas se hace uso de la funcion reshape
arrPar.reshape(11,1)

array([[ 0],
       [ 2],
       [ 4],
       [ 6],
       [ 8],
       [10],
       [12],
       [14],
       [16],
       [18],
       [20]])