# Métodos aritméticos con arrays

In [1]:
#importamos la libreria
import numpy as np

#Creamos una lista con números primos
numPrimos=[2,3,5,7,11,13,17,19,23,29]
numPrimos

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29]

### para realizar la suma de los elementos de un array podemos utilizar sum()

In [4]:
Numeros= np.array(numPrimos)
Numeros

array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29])

In [5]:
Numeros.sum()

np.int64(129)

### para obtener el promedio usamos mean()

In [6]:
Numeros.mean()

np.float64(12.9)

### Para obtener la varianza usamos var()

In [7]:
Numeros.var()

np.float64(73.28999999999999)

### podemos ordenar tambien los elementos de un array 

In [8]:
#Creamos un nuevo array 
arrayFib=([55,0,144,1,21,89,5,8,13,1,34,3,2])
arrayFib

[55, 0, 144, 1, 21, 89, 5, 8, 13, 1, 34, 3, 2]

In [10]:
#Para ordenar de manera ascendente usamos sort
np.sort(arrayFib)

array([  0,   1,   1,   2,   3,   5,   8,  13,  21,  34,  55,  89, 144])

In [14]:
#Para ordenar de manera descendente
np.sort(arrayFib)[::-1]

array([144,  89,  55,  34,  21,  13,   8,   5,   3,   2,   1,   1,   0])

## Seleccionar elementos de un array 
### Podemos selecionar los elementos de un array de tres modos:
### 1.- Seleccionando unicamente un elemento
### 2.- Seleccionar varios elementos al mismo tiempo
### 3.- Usando filtros dentro del array

In [2]:
#Creamos un array con numeros
elementos = np.arange(0,20,2)
elementos

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [6]:
A=elementos.reshape(2,5)
A

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [7]:
#Seleccionamos unicamente un elemento
#Entre corchetes colocaremos la posicion de nuesto elemento en el ejemplo se uso el 4
A[0,2]

np.int64(4)

In [11]:
#Para seleccionar dos elementos o más debemos de colocar ":" lo cual nos seleccionará todos los elementos de X fila o columna
A[:,3]

array([ 6, 16])

In [12]:
#Para seleccionar toda una columba y varios elementos lo hacemos a traves de un rango
A[:,1:3]

array([[ 2,  4],
       [12, 14]])

In [13]:
#para seleccionar valores mayor o menor que "n" es necesario colocar el indicador 

In [ ]:
array<20