# Métodos aritméticos con arrays

In [1]:
#importamos la libreria
import numpy as np

#Creamos una lista con números primos
numPrimos=[2,3,5,7,11,13,17,19,23,29]
numPrimos

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29]

### para realizar la suma de los elementos de un array podemos utilizar sum()

In [4]:
Numeros= np.array(numPrimos)
Numeros

array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29])

In [5]:
Numeros.sum()

np.int64(129)

### para obtener el promedio usamos mean()

In [6]:
Numeros.mean()

np.float64(12.9)

### Para obtener la varianza usamos var()

In [7]:
Numeros.var()

np.float64(73.28999999999999)

### podemos ordenar tambien los elementos de un array 

In [8]:
#Creamos un nuevo array 
arrayFib=([55,0,144,1,21,89,5,8,13,1,34,3,2])
arrayFib

[55, 0, 144, 1, 21, 89, 5, 8, 13, 1, 34, 3, 2]

In [10]:
#Para ordenar de manera ascendente usamos sort
np.sort(arrayFib)

array([  0,   1,   1,   2,   3,   5,   8,  13,  21,  34,  55,  89, 144])

In [14]:
#Para ordenar de manera descendente
np.sort(arrayFib)[::-1]

array([144,  89,  55,  34,  21,  13,   8,   5,   3,   2,   1,   1,   0])

## Seleccionar elementos de un array 